name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # or master, depending on your default branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      # Give the GITHUB_TOKEN write permissions to the repository contents
      contents: write 
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Replace API Key
        run: |
          # Use sed to find and replace the placeholder with the secret API key
          sed -i "s/FIREBASE_API_KEY_PLACEHOLDER/${{ secrets.FIREBASE_API_KEY }}/g" index.html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
